# Generated by Django 5.0.6 on 2024-07-01 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Долгота')),
                ('geocode_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'unique_together': {('lat', 'lon', 'address')},
            },
        ),
    ]
