# Generated by Django 5.0.6 on 2024-06-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('U', 'Необработан'), ('P', 'Готовится'), ('D', 'Доставка'), ('F', 'Выполнен')], db_index=True, default='U', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
